- .gitignore
- package-lock.json
- package.json
- server.js
- src/server.ts
- tsconfig.json
- tslint.json
Add support for typescript on the basic server.
> Add typescript support for basic server

- .env.example
- .gitignore
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
- package.json
- src/server.ts
Add support for docker with make file commands
> Add support for docker with make file commands

- .env.example
- package-lock.json
- package.json
- src/config/initializers/database.ts
- src/controllers/user.controller.ts
- src/db/index.ts
- src/models/user.model.ts
- src/server/index.ts
- src/server/routes.ts
- src/services/db/user.service.ts
Add postgres orm and services layer
> Add postgres orm and services layer

- .env.example
- README.md
- package-lock.json
- package.json
- scripts/db/migrate.ts
- scripts/db/setup.ts
- src/config/index.ts
- src/config/initializers/migrations.ts
- src/controllers/user.controller.ts
- src/db/credentials.ts
- src/index.ts
- src/models/user.model.ts
- src/server/routes.ts
- src/services/db/user.service.ts
- tests/integration/controllers/user.controller.test.ts
- tests/integration/services/db/user.service.test.ts
- tests/integration/setup/clearDB.ts
- tests/unit/config/initializers/envVars.test.ts
- tsconfig.json
add alias support to current modules
> add alias support to current modules

- jest.integration.config.js
- package.json
- scripts/db/migrate.ts
- scripts/db/setup.ts
- tests/integration/services/db/user.service.test.ts
- tests/integration/setup/index.ts
- tsconfig.json
> Fix tests and scripts aliases

- tests/integration/setup/clearDB.ts
- tests/integration/setup/index.ts
Improve test setup performance
- Reviewed possibility of transactions that are currently not available in Sequelize + Jest.
> Improve test setup performance

- package.json
- scripts/db/seed.ts
- src/db/seeds/index.ts
- src/db/seeds/users.seed.ts
> Add db seeds script

- tests/unit/README.md
> Add unit test readme

- README.md
- tests/README.md
Add tests documentation
Issue: #32
> Add tests documentation

- package-lock.json
- package.json
- tests/integration/README.md
- tests/integration/factories/BaseFactory.ts
- tests/integration/factories/UserFactory.ts
- tests/integration/models/user.model.test.ts
Implemented basic fixture method to reuse the model building for integration tests.
Issue: #33 & #34
> Add test fixtures

- README.md
- src/db/README.md
Add database & seed documentation
Issues: #28 & #30
> Add database & seed documentation

- src/controllers/README.md
Add controller documentation
Issue: #37
> Add controller documentation

- package.json
- src/config/index.ts
- src/controllers/docs/property.ts
- src/controllers/index.ts
- src/controllers/property.controller.ts
- src/controllers/types/property.ts
- src/controllers/user.controller.ts
- src/db/migrations/schema/20191020.users.up.sql
- src/db/migrations/schema/20191030.properties.down.sql
- src/db/migrations/schema/20191030.properties.up.sql
- src/db/seeds/index.ts
- src/db/seeds/properties.seed.ts
- src/db/seeds/users.seed.ts
- src/models/base.model.ts
- src/models/index.ts
- src/models/property.model.ts
- src/server/exception.resolver.ts
- src/server/index.ts
- swagger.json
- tests/integration/controllers/user.controller.test.ts
- tests/integration/factories/base.factory.ts
- tests/integration/factories/user.factory.ts
- tests/integration/models/base.model.test.ts
- tests/integration/models/user.model.test.ts
- tests/integration/setup/clearDB.ts
- tslint.json
Add property model with relation
Issue: #38 / AYBP-5
> Add Property model

- .env.example
- scripts/db/setup.ts
- src/db/README.md
- src/db/credentials.ts
- src/db/index.ts
Add ssl support to the db connection to connect to Azure DB.
> Add SSL support for the database

- Dockerfile.prod
- README.md
- build-pipeline.yml
- docker-compose.ci.yml
- docker-compose.dev.yml
- package.json
- scripts/docker/start.sh
- test-pipelines.yml
- tests/unit/config/initializers/envVars.test.ts
Add CI configuration and documentation
Related issue: #43
> Add CI configuration and documentation

- README.md
Add CD configuration and documentation
Issue: #40
> Add CD configuration and documentation

- .prettierrc.js
- package-lock.json
- package.json
Add pre commit hook to review prettier, lint and tests.
> Add precommit hooks to check code

- .env.example
- .env.test
- .gitignore
- docker-compose.yml
- package.json
- scripts/docker/start.sh
Rename the docker-compose yml file for dev to use the default.
Add a new .env variable to allow the user to change the postgres port that will be exposed to the host.
And add the .idea folder to .gitignore.
> Fix the docker NPM scripts

- src/db/migrations/schema/20191020.users.down.sql
- src/db/migrations/schema/20191030.properties.down.sql
- src/db/migrations/schema/20191113.property.user.down.sql
- src/db/migrations/schema/20191113.property.user.up.sql
- Add userId not null constraint.
- Fix down scripts not working since the index is created differently.
> Add userId not null constraint

- src/index.ts
- tests/unit/config/applyConfig.test.ts
- tests/unit/controllers/user.controller.test.ts
Added mock examples for unit tests.
Related issue: #36
> Add mock tests examples on unit tests

- tests/integration/README.md
> Improve test factory documentation

- .prettierrc.js
- README.md
- package-lock.json
- package.json
- scripts/db/migrationRunner/index.ts
- src/db/README.md
- src/db/credentials.ts
- src/db/migrations/data/README.md
- src/index.ts
- tests/README.md
- tests/integration/README.md
- tests/unit/README.md
- tslint.json
This PR is intended to apply a few improvements that have been already implemented in other project repositories.
> Update docs and TSLint config

- .env.example
- .env.test
- docker-compose.ci.yml
- docker-compose.yml
- package-lock.json
- package.json
- scripts/docker/start.sh
- src/db/README.md
- src/db/credentials.ts
- swagger.json
- swaggerConfig.json
This PR removes all references mentioning GraphQL.
Please not that it also removes from the `package.json` the commands:
- `graphql:run`
- `graphql`
> Remove all references of GraphQL

- scripts/db/migrationRunner/index.ts
- scripts/db/setup.ts
This PR to fix the hard reset of the DB
> Fix hard reset of the DB

- package-lock.json
- package.json
- scripts/generator/index.js
- scripts/generator/templates/migrationDown.template
- scripts/generator/templates/migrationUp.template
This PR intends to generate migrations file based on parameters passed to the CLI
It also add a more functional approach to manipulate strings
> Add migration template files and add handy string extensions

- test-pipelines.yml
This PR intends to dockerize everything required to run the testing pipeline. 
It uses services/resources to start a side container for postgres and run the testing steps inside an ubuntu container.
Fore more info: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml
> Containerize the testing pipeline

- Dockerfile
- docker-compose.yml
> Fix server port configuration
